### PR TITLE
Skip device files by default: Use opt.Specials

### LINKED ISSUE #78: Option to preserve special files
Similar to `rsync --specials` an option to handle special files as special is required: Currently the code tries to always copy the *content* of such files, e.g. `/dev/console`, pipes, sockets, … instead of copying it as a special files.
This is causing `kaniko` to stall when building base images: https://github.com/GoogleContainerTools/kaniko/issues/960

### PR DESCRIPTION
**Pull request by otiai10**
Fix #78

### CODE REVIEW

**Comment by otiai10** [comment]
will fix https://github.com/GoogleContainerTools/kaniko/issues/960

**Comment by ajakk** [comment]
I'm hitting the aforementioned kaniko issue. Is anything blocking this? Is testing needed?

**Comment by otiai10** [comment]
this is ready. thx

**Comment by ajakk** [comment]
Thank you!

**Pull request merged**
