### PR TITLE
Fix symlink relative path resolution

### PR DESCRIPTION
**Pull request by LorisFriedel**
fixing #26

### CODE REVIEW

**Comment by otiai10** [comment]
Can you please write a new test case that fails with previous version using `os.Readlink` then we can make sure the exact problem your code will fix?

**Comment by LorisFriedel** [comment]
> Can you please write a new test case that fails with previous version using `os.Readlink` then we can make sure the exact problem your code will fix?

Hello @otiai10 !
I'm not sure to understand what you want me to do?

The fix here is that `os.Readlink` doesn't take into account the symlink file location and the test was not representative of a real use case because the dynamically creating symlink was relative to where the test was executed and not the symlink itself.

PS: for the test coverage verification to pass, do I need to increase it by creating some more tests or is there another way?

Thank you!

**Comment by otiai10** [comment]
I want you to add/fix test cases to let it fail correctly.

Then, fix the source code.

That's my request. Is it possible?

(please don't care about the coverage ;)

**Comment by LorisFriedel** [comment]
> I want you to add/fix test cases to let it fail correctly.
> 
> Then, fix the source code.
> 
> That's my request. Is it possible?
> 
> (please don't care about the coverage ;)

I don't know how (without duplicating the code) I could include in the PR a test case that test the old implementation with `os.ReadLink` AND fix it at the same time?

I'm a bit confused here :/

**Comment by otiai10** [comment]
Separate commits, for example

**Comment by millerlogic** [comment]
Can we please have this fix? Symlink deep copy is broken. Does the new test not fail on the existing code?

**Pull request closed without merging**
