### PR TITLE
Skip by file info too

### PR DESCRIPTION
**Pull request by Antonboom**
Hello!
Thank you for package. 

I faced to a problem when I need to copy all files with a specific extension, but then the Skip() function ignores directories.

Therefore, I propose such a small addition. Thank u!

P.S. Maybe you will rename a package so that it does not conflict with the standard copy function?

### CODE REVIEW

**Comment by otiai10** [comment]
Let me know your thught.

**Comment by Antonboom** [comment]
Good offer! But if an error occurs will I have to panic, since Skip does not return an error-value pair?

What do you think?

**Comment by otiai10** [comment]
Wait... hmm... to make the use cases clear,

1. `yes == true` → Skip it
2. `yes == false` → Do not skip it
3. `error != nil` → Stop copying at all

ok, it makes sense, then. Thanks.

**Comment by otiai10** [comment]
Could you add some comment like this above the `Skip` description.

**Comment by Antonboom** [comment]
Ok, we figured out the Skip function signature. I agree.

Second question. Сan I ignore the `Skip()` for the root entity? Or do you also suggest checking this non-obvious point inside `Skip()`?

**Comment by otiai10** [comment]
IMO, we should ignore `Skip` for root entry by our side, not by user side.

**Comment by otiai10** [comment]
But for now, I don't think creating another function like `copyDispatcher` is a clear solution.
Could you leave that question now and don't include change around `copyDispatcher`?

**Comment by Antonboom** [comment]
In this case, my user-side Skip() will not work correctly, as it will filter the root directory and stop copying.

**Comment by otiai10** [comment]
ah, I implemented that without caring the new `Skip` interface :joy:
Thank you.

**Comment by otiai10** [comment]
Thank you

**Pull request merged**
