### PR TITLE
fix: symlink deep copy with relative path

### LINKED ISSUE #97: Deep symlink copy doesn't work with relative `../foo` target
Deep symlink copy will fail in this situation:

```
test
├── data
│   ├── case00
│   │   └── README.md
│   ├── case01
│   │   └── README.md
│   ├── case02
│   │   └── README.md
│   ├── case03
│   │   ├── README.md
│   │   ├── case01 -> test/data/case01
│   │   └── relative_case01 -> ../case01
```

Though it's entirely acceptable to have a symlink working only at a certain current working dir, most of the time, we have symlinks:
- either to an absolute path
- or relative to itself (eg `../something`). 🐛 **This case doesn't work properly.**

### PR DESCRIPTION
**Pull request by samuel-phan**
fix #97

### CODE REVIEW

**Comment by samuel-phan** [comment]
@otiai10 Any update to merge this fix please?

**Comment by otiai10** [comment]
LGTM

**Comment by otiai10** [comment]
need to be rebased

**Comment by samuel-phan** [comment]
> need to be rebased

Done. Thanks!

**Pull request merged**
