### PR TITLE
Fix build on Apple Silicon

### PR DESCRIPTION
**Pull request by edigaryev**
Don't assume that Darwin is amd64-only.

### CODE REVIEW

**Comment by FabianPonce** [comment]
I ran into this problem and tested this PR on my M1 MacBook and was able to successfully build again. Thanks!

**Review by otiai10 — APPROVED** [review]

**Comment by otiai10** [comment]
Thank you, both!

**Comment by edigaryev** [comment]
@otiai10 Can you also make a patch release? Thanks and happy New Year! 🥳

**Comment by otiai10** [comment]
Sure, gonna do it in 2020, hopefully😆

HNY to you too🥳

**Pull request merged**
