### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by otiai10**

### CODE REVIEW

**Comment by otiai10** [comment]
CC @siscia

**Comment by siscia** [comment]
@otiai10 this is outstanding work! Thanks a lot!

would we also able to cut a release?

**Comment by otiai10** [comment]
@siscia It's shipped with `v1.3.0`, check it out :wink:
https://pkg.go.dev/github.com/otiai10/copy@v1.3.0

**Comment by siscia** [comment]
Thanks a lot!

**Pull request merged**
